# Generated by Django 3.1.3 on 2020-12-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyrecord', '0002_auto_20201215_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
